### PR TITLE
add UuidCodec

### LINKED ISSUE #71: Add UuidCodec

### PR DESCRIPTION
**Pull request by pull-vert**
Fixes #71

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pull-vert Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-h2&pullRequestId=72)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=r2dbc/r2dbc-h2&pullRequestId=72) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@pull-vert Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-h2&pullRequestId=72)!

**Comment by gregturn** [comment]
Resolved via https://github.com/r2dbc/r2dbc-h2/commit/40f65254387774952f08703fbff6b900822a45cd.

Thanks @pull-vert!

**Comment by pull-vert** [comment]
Thanks @gregturn :)

**Pull request closed without merging**
