### PR TITLE
Support for Java 8 date/time

### PR DESCRIPTION
**Pull request by dimone-kun**
Codecs for
- LocalTime
- LocalDate
- LocalDateTime
- OffsetDateTime
- ZonedDateTime

### CODE REVIEW

**Comment by katzyn** [comment]
I think that you shouldn't use legacy `java.sql.*` datetime data type here and especially their buggy data type conversion methods to / from JSR-310 data types that have different known issues with old dates, DST and other transitions, etc.

H2 supports `LocalDate` (`DATE`), `LocalTime` (`TIME [ WITHOUT TIME ZONE ]`), `LocalDateTime` (`TIMESTAMP [ WITHOUT TIME ZONE ]`), `OffsetDateTime` (`TIMESTAMP WITH TIME ZONE`), and `Instant` (`TIMESTAMP WITH TIME ZONE` at UTC) by itself. H2 does not yet support `ZonedDateTime` (and is not required to support it, because JDBC does not use this data type), but you can convert it to `OffsetDateTime` and pass the result to H2. Take a look on `org.h2.util.LocalDateTimeUtils` that has conversion methods to values and back.

**Comment by katzyn** [comment]
> JDBC does not use this data type

I mean that JDBC specification does not mention this data type, but some JDBC drivers support it.

**Comment by dimone-kun** [comment]
> I think that you shouldn't use legacy (and defective by design) ` java.sql.*`

Yeah, you right, sorry. Replaced with `org.h2.util.LocalDateTimeUtils` method calls;

> H2 supports ... `Instant` (`TIMESTAMP WITH TIME ZONE` at UTC) by itself.

Added InstantCodec

**Comment by gregturn** [comment]
Merged to master (and build issues fixed). Thanks @dimone-kun!

**Pull request closed without merging**
