### PR TITLE
Add support for r2dbc exception hierarchy.

### PR DESCRIPTION
**Pull request by gregturn**

### CODE REVIEW

**Comment by katzyn** [comment]
Do you really want to rely on internals of H2 here? Perhaps you can use `instanceof` checks with `java.sql.***Exception` classes instead and possibly move that code from R2DBC-H2 to R2DBC project for possible re-use in other drivers.

**Comment by mp911de** [comment]
Thanks for having a look @katzyn. I second your opinion that checking for JDBC exception subclasses (`SQLTimeoutException`, `SQLSyntaxErrorException`, …) makes more sense than relying directly on H2 classes. R2DBC exceptions are modeled along the lines of JDBC exceptions.

**Comment by mp911de** [comment]
One more thing: 

> code from R2DBC-H2 to R2DBC project for possible re-use in other drivers

We intentionally refrain from using JDBC API in other drivers to keep modules separated. R2DBC H2 is currently (and will hopefully stay so for a long time) the only JDBC to H2 bridge.

**Comment by gregturn** [comment]
Thanks @katzyn and @mp911de. I've updated the code to use standard JDBC exceptions and translate to R2DBC exceptions.

**Pull request closed without merging**
