### PR TITLE
Add basic array support.

### PR DESCRIPTION
**Pull request by alexo134**
Hi,
I'm using ```r2dbc-postgresql``` and text array columns (```text[]```). 
I was unable to the test the code using in memory h2 db because array codec was missing.

### CODE REVIEW

**Comment by mp911de** [comment]
We should set up integrative tests that verify interoperability with various data types to know which array types (and their base column type) we support and which we don't.

**Comment by alexo134** [comment]
Just added array test in the ```CodecIntegrationTests``` class for all executions of ```testType()```:
```java
private void testType(H2Connection connection, String columnType, Object value) {            
    testType(connection, columnType, value, value.getClass(), value);                        
    testType(connection, "ARRAY", new Object[]{value}, Object[].class, actual -> {           
        assertThat(((Object[]) actual)).containsExactly(value);                              
    });                                                                                      
}                                                                                            
```
and got only 5 failed test
image

#shouldEncodeDate
```
Expecting:
  <[2018-11-08T00:00:00.000]>
to contain exactly (and in same order):
  <[2018-11-08]>
but some elements were not found:
  <[2018-11-08]>
and others were not expected:
  <[2018-11-08T00:00:00.000]>
```
#shouldEncodeTime
```
Expecting:
  <[1970-01-01T11:08:27.100]>
to contain exactly (and in same order):
  <[11:08:27.100]>
but some elements were not found:
  <[11:08:27.100]>
and others were not expected:
  <[1970-01-01T11:08:27.100]>
```
#shouldEncodeDateTime2
```
Expecting:
  <[2018-11-08T11:08:28.200]>
to contain exactly (and in same order):
  <[2018-11-08T11:08:28.200]>
but some elements were not found:
  <[2018-11-08T11:08:28.200]>
and others were not expected:
  <[2018-11-08T11:08:28.200]>
```
#shouldEncodeOffsetDateTimeAsTimestampWithTimeZone
```
Expecting:
  <[2018-08-27 17:41:14.89+00:45]>
to contain exactly (and in same order):
  <[2018-08-27T17:41:14.890+00:45]>
but some elements were not found:
  <[2018-08-27T17:41:14.890+00:45]>
and others were not expected:
  <[2018-08-27 17:41:14.89+00:45]>
```
#shouldEncodeDateTime
```
Expecting:
  <[2018-11-08T11:08:28.200]>
to contain exactly (and in same order):
  <[2018-11-08T11:08:28.200]>
but some elements were not found:
  <[2018-11-08T11:08:28.200]>
and others were not expected:
  <[2018-11-08T11:08:28.200]>
```

**Comment by nearsyh** [comment]
Thanks for your work. Any updates / plan on this PR?

**Comment by mp911de** [comment]
Looking at this PR, it's in a broken state that requires rebasing.

**Comment by alexo134** [comment]
I've resolved conflicts.

The problem is that I haven't tested it recently. But It passed in the CI pipelines.

**Comment by gregturn** [comment]
Thanks @alexo134. I’ll try to review it this week.

**Comment by gregturn** [comment]
Merged to 0.8.x.

**Comment by gregturn** [comment]
Merged forward to `master`.

**Comment by gregturn** [comment]
Thanks @alexo134!

**Pull request closed without merging**
