### PR TITLE
search for question mark as query input parameter

### PR DESCRIPTION
**Pull request by uaihebert**
we have two groups on the new regex pattern.

on the first pattern we search for the symbols ? or $. In the second one we search for the position

#7

### CODE REVIEW

**Comment by mp911de** [comment]
Looks reasonable to me. Based on #7, we should switch to questionmark (`?<index>`) syntax as the default r2dbc-h2 parameter bind markers. Toughts @gregturn.

Doing so would also require to update the readme file.

**Comment by uaihebert** [comment]
I did like this based on this OR `(Or consider supporting BOTH versions!)` that was written on the ticket. I could do this switch also.

Let us hear what @gregturn has to say. ( :

**Comment by mp911de** [comment]
Not saying we should remove the dollar notation, just promote the questionmark one.

**Comment by nebhale** [comment]
I'm surprised to see the `?#` notation as it's not something I've ever seen before.  Given that H2's internal model is effectively JDBC (we've seen it leak out in other places), I would have expected that the replacement be `?` only.  In other words, I'd expect the following:

```java
createStatement("INSERT INTO test VALUES(?)").bind(0, 100)      // valid
createStatement("INSERT INTO test VALUES(?)").bind("?", 100)    // invalid
createStatement("INSERT INTO test VALUES($1)").bind("$1", 100)  // valid
createStatement("INSERT INTO test VALUES($1)").bind(0, 100)     // valid
```

**Comment by uaihebert** [comment]
hello @nebhale 

what about this? should this be valid?
```java
createStatement("INSERT INTO test VALUES(?)").bind("?1", 100)
```

**Comment by mp911de** [comment]
See for reference: 

https://github.com/h2database/h2database/blob/master/h2/src/main/org/h2/command/Parser.java#L3849-L3864

**Comment by uaihebert** [comment]
Got it.

What is lacking in this PR? Could I say that is:
1) Update the Readme
2) if bind param has only `?` or `? 1` it should be invalid

**Comment by nebhale** [comment]
Interesting @mp911de I was totally unaware of that.  Then I think the requirements actually are:

```java
createStatement("INSERT INTO test VALUES(?)").bind("?", 100)    // invalid
createStatement("INSERT INTO test VALUES(?)").bind(0, 100)      // valid
createStatement("INSERT INTO test VALUES(?1)").bind("?1", 100)  // valid
createStatement("INSERT INTO test VALUES(?1)").bind(0, 100)     // valid
createStatement("INSERT INTO test VALUES($1)").bind("$1", 100)  // valid
createStatement("INSERT INTO test VALUES($1)").bind(0, 100)     // valid
```

**Comment by uaihebert** [comment]
hello @nebhale I was looking at the code, and right now we only accept binding as string:

```java
@Override
public H2Statement bind(Object identifier, Object value) {
    Assert.requireNonNull(identifier, "identifier must not be null");
    Assert.requireType(identifier, String.class, "identifier must be a String");

    return bind(getIndex((String) identifier), value);
}
```

I will add tests to cover what you wrote as valid or invalid, but I will only use string for now.

**Comment by uaihebert** [comment]
@nebhale @mp911de 

I added another test to cover the cases defined as invalid for only `$` or `?`.

I believe that if we want to support integer as bind params, it would be good to do it in a separated task. ( :

**Comment by mp911de** [comment]
The PR looks good to me. Let's hear what @gregturn says. Regarding index-based binding: Do you want to file a ticket and describe the approach @uaihebert?

**Comment by uaihebert** [comment]
@mp911de sure, will do it in the next couple of hours. ( :

**Comment by uaihebert** [comment]
done: https://github.com/r2dbc/r2dbc-h2/issues/45

**Comment by uaihebert** [comment]
hello @mp911de when do you think we could finish this? 

I will start working on the #45 and it depends on this code. ( :

for now I will start working and push to my branch but I will not open the PR.

**Comment by gregturn** [comment]
Resolved via https://github.com/r2dbc/r2dbc-h2/commit/70aa32e431d4012340848777d73640e75459e053 and https://github.com/r2dbc/r2dbc-h2/commit/062f47bca04c340d595295842585109d6317ec81.

**Pull request closed without merging**
